### ISSUE TITLE
为什么不开源呢？

### ISSUE THREAD

**Issue by panchangxin123** [cdians/FastChia#1]
为什么不开源呢？如果不开源如何消除大家的疑虑呢？

**Comment by cdians** [comment]
正在整理项目，近期会完成开源发自我的华为手机-------- 原始邮件 --------发件人： panchangxin123 ***@***.***>日期： 2021年5月5日周三 18:17收件人： cdians/FastChia ***@***.***>抄送： Subscribed ***@***.***>主    题： [cdians/FastChia] 为什么不开源呢？ (#1)

为什么不开源呢？如果不开源如何消除大家的疑虑呢？

**Comment by elevenstyle** [comment]
> 为什么不开源呢？如果不开源如何消除大家的疑虑呢？

.net 开发的,开不开源有区别吗
